version: "3"
services:
 app:
  container_name: blind_command_injection_lab
  depends_on:
   - redis_db
  build: .
  restart: always
  ports:
   - "5000:5000"
 redis_db:
  container_name: redis_cache
  image: "redis:latest"
  restart: always
  ports:
   - "6379:6379"